-- MySQL Script generated by MySQL Workbench
-- Sat May 25 14:56:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema web-scraping-db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `web-scraping-db` ;

-- -----------------------------------------------------
-- Schema web-scraping-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `web-scraping-db` DEFAULT CHARACTER SET utf8 ;
USE `web-scraping-db` ;

-- -----------------------------------------------------
-- Table `cufes_information`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cufes_information` ;

CREATE TABLE IF NOT EXISTS `cufes_information` (
  `cufes_information_id` INT NOT NULL AUTO_INCREMENT,
  `cufes` VARCHAR(255) NULL,
  `extracted_data` JSON NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`cufes_information_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
